seml:
  name: neurips_smoothing
  db_collection: neurips_smoothing
  executable: experiment_smoothing.py
  conda_environment: neurips20
  project_root_dir: ../..
  output_dir: seml/smoothing/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 5-00:00     # max time, D-HH:MM

fixed:
  n_samples_pre_eval: 100
  conf_alpha: 0.05
  batch_size: 1
  artifact_dir: cache
  smoothing_result_storage_type: smoothing
  model_storage_type: pretrained
  device: 0

grid:
  dataset:
    type: choice
    options:
      - pubmed

  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

  sample_params:
    type: choice
    options:
    - pf_plus_att: 0
      pf_minus_att: 0
      pf_plus_adj: 0.001
      pf_minus_adj: 0
      n_samples: 10_000
    - pf_plus_att: 0
      pf_minus_att: 0
      pf_plus_adj: 0
      pf_minus_adj: 0.4
      n_samples: 10_000
    - pf_plus_att: 0
      pf_minus_att: 0
      pf_plus_adj: 0.001
      pf_minus_adj: 0.4
      n_samples: 10_000
    