seml:
  name: neurips_train
  db_collection: neurips_train
  executable: experiment_train.py
  conda_environment: neurips20

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-01:00     # max time, D-HH:MM

fixed:
  train_params:
    lr: 1e-2
    weight_decay: 1e-3
    patience: 300
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0

grid:
  dataset:
    type: choice
    options:
      - cora_ml
      - citeseer

  binary_attr:
    type: choice
    options:
      - True
      - False

  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

gcn:
  fixed:
    model_params:
      label: Vanilla GCN
      model: GCN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      svd_params: None
      jaccard_params: None
      gdc_params: None

gdc:
  fixed:
    model_params:
      label: Vanilla GDC
      model: GCN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      svd_params: None
      jaccard_params: None
      gdc_params:
          alpha: 0.15
          k: 64
          # use_cpu: False

soft_medoid_gdc_t1_0:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=1.0)
      model: RGNN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      mean: soft_k_medoid
      mean_kwargs:
          k: 64
          temperature: 1.0
          # with_weight_correction: True
      svd_params: None
      jaccard_params: None
      gdc_params:
          alpha: 0.15
          k: 64
          # use_cpu: False

soft_medoid_gdc_t0_5:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=0.5)
      model: RGNN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      mean: soft_k_medoid
      mean_kwargs:
          k: 64
          temperature: 0.5
          # with_weight_correction: True
      svd_params: None
      jaccard_params: None
      gdc_params:
          alpha: 0.15
          k: 64
          # use_cpu: False

soft_medoid_gdc_t0_2:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=0.2)
      model: RGNN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      mean: soft_k_medoid
      mean_kwargs:
          k: 64
          temperature: 0.2
          # with_weight_correction: True
      svd_params: None
      jaccard_params: None
      gdc_params:
          alpha: 0.15
          k: 64
          # use_cpu: False

svd:
  fixed:
    model_params:
      label: SVD GCN
      model: GCN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      svd_params: 
        rank: 50
      jaccard_params: None
      gdc_params: None

jaccard:
  fixed:
    model_params:
      label: Jaccard GCN
      model: GCN
      do_cache_adj_prep: True
      n_filters: 64
      dropout: 0.5
      svd_params: None
      jaccard_params: 
        threshold: 0.01
      gdc_params: None

rgcn:
  fixed:
    model_params:
      label: RGCN
      model: RGCN
      do_cache_adj_prep: True
      n_filters: 64
      svd_params: None
      jaccard_params: None
      gdc_params: None
