seml:
  name: neurips_train
  db_collection: neurips_train
  executable: experiment_train.py
  conda_environment: neurips20
  project_root_dir: ../..
  output_dir: seml/train/output

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 16G          # memory
    cpus-per-task: 4  # num cores
    time: 0-08:00     # max time, D-HH:MM

fixed:
  train_params:
    lr: 1e-2
    weight_decay: 1e-3
    patience: 300
    max_epochs: 3000
  artifact_dir: cache
  model_storage_type: pretrained
  device: 0

grid:
  dataset:
    type: choice
    options:
      - pubmed

  binary_attr:
    type: choice
    options:
      - True
      - False
      
  seed:
    type: choice
    options:
      - 0
      - 1
      - 5

gcn:
  fixed:
    model_params:
      label: Vanilla GCN
      model: GCN
      dropout: 0.5
      n_filters: 64
      gdc_params: None
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

gdc:
  fixed:
    model_params:
      label: Vanilla GDC
      model: GCN
      dropout: 0.5
      n_filters: 64
      gdc_params:
          alpha: 0.15
          k: 32
          use_cpu: False
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

soft_medoid_gdc_t1_0:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=1.0)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_k_medoid
      mean_kwargs:
          k: 32
          temperature: 1.0
          # with_weight_correction: True
      gdc_params:
          alpha: 0.15
          k: 32
          # use_cpu: False
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

soft_medoid_gdc_t0_5:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=0.5)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_k_medoid
      mean_kwargs:
          k: 32
          temperature: 0.5
          # with_weight_correction: True
      gdc_params:
          alpha: 0.15
          k: 32
          # use_cpu: False
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True

soft_medoid_gdc_t0_2:
  fixed:
    model_params:
      label: Soft Medoid GDC (T=0.2)
      model: RGNN
      dropout: 0.5
      n_filters: 64
      mean: soft_k_medoid
      mean_kwargs:
          k: 32
          temperature: 0.2
          # with_weight_correction: True
      gdc_params:
          alpha: 0.15
          k: 32
          # use_cpu: False
      svd_params: None
      jaccard_params: None
      do_cache_adj_prep: True
